[2023-07-29T12:48:12.196+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_postgres_dag_v3.insert_data scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-29T12:48:12.555+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_postgres_dag_v3.insert_data scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-29T12:48:12.579+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T12:48:12.705+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2023-07-29T12:48:12.706+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T12:48:13.650+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2023-07-27 00:00:00+00:00
[2023-07-29T12:48:13.755+0000] {standard_task_runner.py:55} INFO - Started process 5780 to run task
[2023-07-29T12:48:13.782+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_postgres_dag_v3', 'insert_data', 'scheduled__2023-07-27T00:00:00+00:00', '--job-id', '2047', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_v2-2.py', '--cfg-path', '/tmp/tmpxhtf1mif']
[2023-07-29T12:48:13.796+0000] {standard_task_runner.py:83} INFO - Job 2047: Subtask insert_data
[2023-07-29T12:48:15.077+0000] {task_command.py:389} INFO - Running <TaskInstance: my_postgres_dag_v3.insert_data scheduled__2023-07-27T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T12:48:18.479+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Byron
AIRFLOW_CTX_DAG_ID=my_postgres_dag_v3
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-27T00:00:00+00:00
[2023-07-29T12:48:18.497+0000] {sql.py:253} INFO - Executing: INSERT INTO ***_users (name) VALUES ("Chidi", "Joseph", "Cindy", "Sarai")
[2023-07-29T12:48:18.744+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T12:48:26.739+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T12:48:26.845+0000] {sql.py:364} INFO - Running statement: INSERT INTO ***_users (name) VALUES ("Chidi", "Joseph", "Cindy", "Sarai"), parameters: None
[2023-07-29T12:48:26.869+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Chidi" does not exist
LINE 1: INSERT INTO ***_users (name) VALUES ("Chidi", "Joseph", ...
                                                 ^

[2023-07-29T12:48:26.959+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=my_postgres_dag_v3, task_id=insert_data, execution_date=20230727T000000, start_date=20230729T124812, end_date=20230729T124826
[2023-07-29T12:48:27.132+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2047 for task insert_data (column "Chidi" does not exist
LINE 1: INSERT INTO ***_users (name) VALUES ("Chidi", "Joseph", ...
                                                 ^
; 5780)
[2023-07-29T12:48:27.290+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T12:48:27.551+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
