[2023-07-29T15:28:55.021+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-29T15:28:55.761+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-29T15:28:55.867+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:28:55.970+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-07-29T15:28:55.971+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:28:56.606+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): write_to_postgres> on 2023-07-02 00:00:00+00:00
[2023-07-29T15:28:56.661+0000] {standard_task_runner.py:55} INFO - Started process 13717 to run task
[2023-07-29T15:28:56.771+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'write_to_postgres', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '2817', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmp9kklbckt']
[2023-07-29T15:28:56.780+0000] {standard_task_runner.py:83} INFO - Job 2817: Subtask write_to_postgres
[2023-07-29T15:28:58.629+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.write_to_postgres scheduled__2023-07-02T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T15:29:02.588+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=write_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-07-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-02T00:00:00+00:00
[2023-07-29T15:29:03.159+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T15:29:03.680+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_v3.py", line 73, in write_to_postgres
    execute_values(cursor, insert_statement, [tuple(x) for x in df.to_records(index=False)])
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'
[2023-07-29T15:29:04.114+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_engineering_jobs_dags_v3, task_id=write_to_postgres, execution_date=20230702T000000, start_date=20230729T152855, end_date=20230729T152904
[2023-07-29T15:29:04.626+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2817 for task write_to_postgres (can't adapt type 'dict'; 13717)
[2023-07-29T15:29:05.289+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T15:29:05.758+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
