[2023-07-29T15:55:28.418+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.create_table scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-07-29T15:55:28.897+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineering_jobs_dags_v3.create_table scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-07-29T15:55:28.921+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:55:28.930+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-07-29T15:55:28.937+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-29T15:55:30.051+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table> on 2023-07-20 00:00:00+00:00
[2023-07-29T15:55:30.315+0000] {standard_task_runner.py:55} INFO - Started process 14943 to run task
[2023-07-29T15:55:30.308+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineering_jobs_dags_v3', 'create_table', 'scheduled__2023-07-20T00:00:00+00:00', '--job-id', '2892', '--raw', '--subdir', 'DAGS_FOLDER/load_data_v3.py', '--cfg-path', '/tmp/tmp13knt41o']
[2023-07-29T15:55:30.985+0000] {standard_task_runner.py:83} INFO - Job 2892: Subtask create_table
[2023-07-29T15:55:33.282+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineering_jobs_dags_v3.create_table scheduled__2023-07-20T00:00:00+00:00 [running]> on host f1ea17bde741
[2023-07-29T15:55:36.933+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_engineering_jobs_dags_v3
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-20T00:00:00+00:00
[2023-07-29T15:55:36.942+0000] {sql.py:253} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS jobs(
            id VARCHAR(255),
            salary_min DECIMAL,
            salary_max DECIMAL,
            description TEXT,
            category VARCHAR(255),
            label VARCHAR(255),
            tag VARCHAR(255),
            location TEXT,
            longitude DECIMAL,
            latitude DECIMAL,
            job_title VARCHAR(255),
            salary_is_predicted BOOLEAN,
            adref VARCHAR(255),
            created TIMESTAMP,
            title VARCHAR(255),
            redirect_url TEXT,
            company TEXT,
            class VARCHAR(255),
            area TEXT
        )
    
[2023-07-29T15:55:37.103+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T15:56:12.012+0000] {base.py:73} INFO - Using connection ID 'my_connection' for task execution.
[2023-07-29T15:56:12.376+0000] {sql.py:364} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS jobs(
            id VARCHAR(255),
            salary_min DECIMAL,
            salary_max DECIMAL,
            description TEXT,
            category VARCHAR(255),
            label VARCHAR(255),
            tag VARCHAR(255),
            location TEXT,
            longitude DECIMAL,
            latitude DECIMAL,
            job_title VARCHAR(255),
            salary_is_predicted BOOLEAN,
            adref VARCHAR(255),
            created TIMESTAMP,
            title VARCHAR(255),
            redirect_url TEXT,
            company TEXT,
            class VARCHAR(255),
            area TEXT
        )
    , parameters: None
[2023-07-29T15:56:13.535+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(jobs, 2200) already exists.

[2023-07-29T15:56:14.052+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_engineering_jobs_dags_v3, task_id=create_table, execution_date=20230720T000000, start_date=20230729T155528, end_date=20230729T155614
[2023-07-29T15:56:17.906+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2892 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(jobs, 2200) already exists.
; 14943)
[2023-07-29T15:56:18.403+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-29T15:56:19.268+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
